CREATE TABLE produtos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(255) NOT NULL,
    descricao         VARCHAR(255),
    preco             NUMERIC(10, 2) NOT NULL,
    quantidade_estoque INTEGER NOT NULL,
    ativo             BOOLEAN NOT NULL,
    criado_em         TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em     TIMESTAMP WITH TIME ZONE
);
