CREATE TABLE fish (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    region      VARCHAR(255),
    type        VARCHAR(50) NOT NULL,
    icon_path   VARCHAR(512),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_fish_name UNIQUE (name)
);
