CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE water_body (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    water_type VARCHAR(50) NOT NULL,
    geom geometry(Geometry, 4326) NOT NULL,
    osm_id BIGINT,
    source VARCHAR(50) NOT NULL DEFAULT 'OSM',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_water_body_geom ON water_body USING GIST (geom);
CREATE UNIQUE INDEX uk_water_body_osm ON water_body (osm_id) WHERE osm_id IS NOT NULL;
