CREATE TABLE catch_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    water_body_id BIGINT NOT NULL REFERENCES water_body(id),
    location geometry(Point, 4326) NOT NULL,
    location_visibility VARCHAR(20) NOT NULL,
    species_id BIGINT NOT NULL REFERENCES fish(id),
    weight_grams INT,
    length_mm INT,
    description TEXT,
    fishing_method VARCHAR(20) NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    caught_at TIMESTAMP WITH TIME ZONE NOT NULL,
    weather_temperature_c NUMERIC(4,1),
    weather_condition VARCHAR(32),
    weather_wind_speed_kmh NUMERIC(5,1),
    weather_wind_direction_deg INT,
    weather_humidity_pct INT,
    weather_pressure_hpa NUMERIC(6,1),
    weather_code INT,
    weather_captured_at TIMESTAMP WITH TIME ZONE,
    weather_source VARCHAR(32),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_catch_location ON catch_record USING GIST (location);
CREATE INDEX idx_catch_user ON catch_record (user_id);
CREATE INDEX idx_catch_species ON catch_record (species_id);

CREATE TABLE catch_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catch_record_id BIGINT NOT NULL REFERENCES catch_record(id) ON DELETE CASCADE,
    file_path VARCHAR(512) NOT NULL,
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_catch_photo_record ON catch_photo (catch_record_id);
