-- Estabelecimentos de pesca (POIs): lojas, pesqueiros, iscarias, marinas, rampas, clubes.
-- Modelados como ponto geográfico (lat/lon), com busca por proximidade, nome e categoria.
CREATE TABLE establishment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(40) NOT NULL,
    address VARCHAR(512),
    phone VARCHAR(40),
    geom geometry(Point, 4326) NOT NULL,
    osm_id BIGINT,
    source VARCHAR(50) NOT NULL DEFAULT 'OSM',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_establishment_geom ON establishment USING GIST (geom);
CREATE INDEX idx_establishment_category ON establishment (category);
CREATE UNIQUE INDEX uk_establishment_osm ON establishment (osm_id) WHERE osm_id IS NOT NULL;
